# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# Custom variables: accessible in templates via {{ site.myvariable }}.

title: Imaging-PHD
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Imaging-PHD project is building a scalable cyberinfrastructure framework to capture, store, and disseminate persistent and machine-actionable metadata describing microscopy hardware configurations at the time of data acquisition
  This project is a proof of concept of clear, standardized records of the equipment used in research. These records, known as Persistent Hardware Descriptors (PHDs), are stored permanently and can be directly linked to scientific data and publications.
logo: /assets/images/IPHD_logo_small.png
baseurl: "/imaging-phd" # site subpath (relative to organization GitHub)
url: "https://Persistent-Hardware-Descriptor-Project.github.io/imaging-phd" # the base hostname & protocol 
# github_username:  jcpetitto
email: caterina.strambio@umassmed.edu

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  team:
    output: true
    permalink: /about/team/:name/

# sets the defaults for each member of a collection
defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: team-member

# Items or directories excluded from processing
# exclude:
#   - dir_to_exclude/
# the below are excluded by default
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
# Process excluded items explicitly listing the directories or file path in the `include:` list.
# include:
#   - dir_to_include/